sudo: required

dist: xenial

addons:
  apt:
    packages:
      - sshpass

branches:
  only:
    - master

language:
  - python

python:
  - "3.5"

script:
  - sh ./backend/travis.sh
  - sh ./frontend/travis.sh
