sudo: required

dist: xenial

branches:
  only:
    - master

addons:
  ssh_known_hosts:
  - 138.68.65.124

language:
  - python

python:
  - "3.5"

script:
  - sh ./backend/travis.sh
  - sh ./frontend/travis.sh
